# Yarn configuration for Obsidian STA Plugin

# Use node_modules for better compatibility
nodeLinker: node-modules

# Disable telemetry for privacy
enableTelemetry: false

# Network settings
networkTimeout: 60000
httpTimeout: 60000

# Cache settings
enableGlobalCache: true

# Progress display
progressBarStyle: modern
