import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Ensure dist directory exists
const distDir = 'dist';
if (!existsSync(distDir)) {
	mkdirSync(distDir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: join(distDir, 'main.js'),
});

// Function to copy additional files to dist
function copyFilesToDist() {
	const filesToCopy = [
		'manifest.json',
		'src/styles.css',
		'versions.json'
	];

	filesToCopy.forEach(file => {
		const fileName = file.includes('/') ? file.split('/').pop() : file;
		const destPath = join(distDir, fileName);

		if (existsSync(file)) {
			copyFileSync(file, destPath);
			console.log(`Copied ${file} to ${distDir}/${fileName}`);
		} else {
			console.warn(`Warning: ${file} not found, skipping...`);
		}
	});
}

if (prod) {
	await context.rebuild();
	copyFilesToDist();
	console.log('Production build complete! Files are in the dist/ directory.');
	process.exit(0);
} else {
	await context.watch();
	copyFilesToDist();
	console.log('Development build started with watching...');
}
